const motivationalQuotes = [
  { quote: "The only way to do great work is to love what you do.", speaker: "Steve Jobs" },
  { quote: "Innovation distinguishes between a leader and a follower.", speaker: "Steve Jobs" },
  { quote: "It does not matter how slowly you go as long as you do not stop.", speaker: "Confucius" },
  { quote: "Everything you've ever wanted is on the other side of fear.", speaker: "George Addair" },
  { quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", speaker: "Winston Churchill" },
  { quote: "Hardships often prepare ordinary people for an extraordinary destiny.", speaker: "C.S. Lewis" },
  { quote: "Believe you can and you're halfway there.", speaker: "Theodore Roosevelt" },
  { quote: "Your time is limited, so don't waste it living someone else's life.", speaker: "Steve Jobs" },
  { quote: "The future belongs to those who believe in the beauty of their dreams.", speaker: "Eleanor Roosevelt" },
  { quote: "Do what you can, with what you have, where you are.", speaker: "Theodore Roosevelt" },
  { quote: "The only limit to our realization of tomorrow will be our doubts of today.", speaker: "Franklin D. Roosevelt" },
  { quote: "The way to get started is to quit talking and begin doing.", speaker: "Walt Disney" },
  { quote: "Don't watch the clock; do what it does. Keep going.", speaker: "Sam Levenson" },
  { quote: "Aim for the moon. If you miss, you may hit a star.", speaker: "W. Clement Stone" },
  { quote: "Keep your face always toward the sunshine—and shadows will fall behind you.", speaker: "Walt Whitman" },
  { quote: "Success usually comes to those who are too busy to be looking for it.", speaker: "Henry David Thoreau" },
  { quote: "Whether you think you can or you think you can’t, you’re right.", speaker: "Henry Ford" },
  { quote: "Action is the foundational key to all success.", speaker: "Pablo Picasso" },
  { quote: "Dream big and dare to fail.", speaker: "Norman Vaughan" },
  { quote: "It always seems impossible until it's done.", speaker: "Nelson Mandela" },
  { quote: "Don’t let yesterday take up too much of today.", speaker: "Will Rogers" },
  { quote: "You miss 100% of the shots you don’t take.", speaker: "Wayne Gretzky" },
  { quote: "I find that the harder I work, the more luck I seem to have.", speaker: "Thomas Jefferson" },
  { quote: "Opportunities don't happen. You create them.", speaker: "Chris Grosser" },
  { quote: "Try not to become a man of success, but rather try to become a man of value.", speaker: "Albert Einstein" },
  { quote: "The secret of getting ahead is getting started.", speaker: "Mark Twain" },
  { quote: "Don't be afraid to give up the good to go for the great.", speaker: "John D. Rockefeller" },
  { quote: "I never dreamed about success. I worked for it.", speaker: "Estée Lauder" },
  { quote: "The only place where success comes before work is in the dictionary.", speaker: "Vidal Sassoon" },
  { quote: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", speaker: "Eleanor Roosevelt" },
  { quote: "Success is walking from failure to failure with no loss of enthusiasm.", speaker: "Winston Churchill" },
  { quote: "The best revenge is massive success.", speaker: "Frank Sinatra" },
  { quote: "The function of leadership is to produce more leaders, not more followers.", speaker: "Ralph Nader" },
  { quote: "Do one thing every day that scares you.", speaker: "Eleanor Roosevelt" },
  { quote: "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.", speaker: "Jordan Belfort" },
  { quote: "You can't use up creativity. The more you use, the more you have.", speaker: "Maya Angelou" },
  { quote: "Go confidently in the direction of your dreams. Live the life you have imagined.", speaker: "Henry David Thoreau" },
  { quote: "I would rather die of passion than of boredom.", speaker: "Vincent van Gogh" },
  { quote: "Life is what happens when you're busy making other plans.", speaker: "John Lennon" },
  { quote: "It is never too late to be what you might have been.", speaker: "George Eliot" },
  { quote: "Start where you are. Use what you have. Do what you can.", speaker: "Arthur Ashe" },
  { quote: "Fall seven times and stand up eight.", speaker: "Japanese Proverb" },
  { quote: "Everything has beauty, but not everyone sees it.", speaker: "Confucius" },
  { quote: "Happiness is not something readymade. It comes from your own actions.", speaker: "Dalai Lama" },
  { quote: "If you want to lift yourself up, lift up someone else.", speaker: "Booker T. Washington" },
  { quote: "Limit your 'always' and your 'nevers.'", speaker: "Amy Poehler" },
  { quote: "The best time to plant a tree was 20 years ago. The second best time is now.", speaker: "Chinese Proverb" },
  { quote: "Change your thoughts and you change your world.", speaker: "Norman Vincent Peale" },
  { quote: "Either you run the day, or the day runs you.", speaker: "Jim Rohn" },
  { quote: "An unexamined life is not worth living.", speaker: "Socrates" },
  { quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.", speaker: "Zig Ziglar" },
  { quote: "The mind is everything. What you think you become.", speaker: "Buddha" },
  { quote: "A person who never made a mistake never tried anything new.", speaker: "Albert Einstein" },
  { quote: "If you can dream it, you can do it.", speaker: "Walt Disney" },
  { quote: "Your problem isn't the problem. Your reaction is the problem.", speaker: "Anonymous" },
  { quote: "The distance between insanity and genius is measured only by success.", speaker: "Bruce Feirstein" },
  { quote: "When you stop dreaming you stop living.", speaker: "Malcolm Forbes" },
  { quote: "The more I want to get something done, the less I call it work.", speaker: "Richard Bach" },
  { quote: "Small deeds done are better than great deeds planned.", speaker: "Peter Marshall" },
  { quote: "Don't judge each day by the harvest you reap but by the seeds that you plant.", speaker: "Robert Louis Stevenson" },
  { quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.", speaker: "Ralph Waldo Emerson" },
  { quote: "Life is 10% what happens to me and 90% of how I react to it.", speaker: "Charles Swindoll" },
  { quote: "There is no substitute for hard work.", speaker: "Thomas Edison" },
  { quote: "If you're going through hell, keep going.", speaker: "Winston Churchill" },
  { quote: "Energy and persistence conquer all things.", speaker: "Benjamin Franklin" },
  { quote: "The successful warrior is the average man, with laser-like focus.", speaker: "Bruce Lee" },
  { quote: "The power of imagination makes us infinite.", speaker: "John Muir" },
  { quote: "To be the best, you must be able to handle the worst.", speaker: "Wilson Kanadi" },
  { quote: "Failure is the condiment that gives success its flavor.", speaker: "Truman Capote" },
  { quote: "Stay hungry, stay foolish.", speaker: "Steve Jobs" },
  { quote: "Everything you can imagine is real.", speaker: "Pablo Picasso" },
  { quote: "I have not failed. I've just found 10,000 ways that won't work.", speaker: "Thomas Edison" },
  { quote: "You must be the change you wish to see in the world.", speaker: "Mahatma Gandhi" },
  { quote: "Imagination is more important than knowledge.", speaker: "Albert Einstein" },
  { quote: "If you tell the truth, you don't have to remember anything.", speaker: "Mark Twain" },
  { quote: "Quality is not an act, it is a habit.", speaker: "Aristotle" },
  { quote: "Life is short, and it is up to you to make it sweet.", speaker: "Sarah Louise Delany" },
  { quote: "If you spend too much time thinking about a thing, you’ll never get it done.", speaker: "Bruce Lee" },
  { quote: "Keep going. Everything you need will come to you at the perfect time.", speaker: "Anonymous" },
  { quote: "Be yourself; everyone else is already taken.", speaker: "Oscar Wilde" },
  { quote: "Believe in yourself and all that you are.", speaker: "Christian D. Larson" },
  { quote: "In the middle of every difficulty lies opportunity.", speaker: "Albert Einstein" },
  { quote: "It’s not whether you get knocked down, it’s whether you get up.", speaker: "Vince Lombardi" },
  { quote: "The road to success and the road to failure are almost exactly the same.", speaker: "Colin R. Davis" },
  { quote: "Don’t count the days, make the days count.", speaker: "Muhammad Ali" },
  { quote: "Strength does not come from physical capacity. It comes from an indomitable will.", speaker: "Mahatma Gandhi" },
  { quote: "The only limit to our realization of tomorrow is our doubts of today.", speaker: "Franklin D. Roosevelt" },
  { quote: "Act as if what you do makes a difference. It does.", speaker: "William James" },
  { quote: "Success is getting what you want. Happiness is wanting what you get.", speaker: "Dale Carnegie" },
  { quote: "Everything is possible for him who believes.", speaker: "Anonymous" },
  { quote: "Work hard in silence, let your success be your noise.", speaker: "Frank Ocean" },
  { quote: "What we achieve inwardly will change outer reality.", speaker: "Plutarch" },
  { quote: "It’s not the years in your life that count. It’s the life in your years.", speaker: "Abraham Lincoln" },
  { quote: "Difficulties strengthen the mind, as labor does the body.", speaker: "Seneca" },
  { quote: "Persistence guarantees that results are inevitable.", speaker: "Paramahansa Yogananda" },
  { quote: "Turn your wounds into wisdom.", speaker: "Oprah Winfrey" },
  { quote: "The secret of your future is hidden in your daily routine.", speaker: "Mike Murdock" },
  { quote: "If you want to achieve greatness stop asking for permission.", speaker: "Anonymous" },
  { quote: "Do not wait for leaders; do it alone, person to person.", speaker: "Mother Teresa" },
  { quote: "He who has a why to live can bear almost any how.", speaker: "Friedrich Nietzsche" }
];

// btn event 
const btn = document.getElementById("change");
const qoute = document.querySelector('h1');
const speaker = document.getElementById('speaker');

btn.addEventListener('click', () =>{
  const index = Math.floor(Math.random()*100);
  qoute.innerText = `${motivationalQuotes[index].quote}`;
  speaker.innerText=`${motivationalQuotes[index].speaker}`;


    
});

// acces qoute 

